In [1]:
 import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

In [2]:

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

In [7]:
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
       SELECT f.name AS facility, SUM(CASE WHEN b.memid = 0 THEN guestcost*slots ELSE membercost*slots END) AS revenue
FROM Facilities AS f
LEFT JOIN Bookings AS b
USING (facid)
GROUP BY facility
HAVING revenue < 1000
ORDER BY revenue;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Table Tennis', 180)
('Snooker Table', 240)
('Pool Table', 270)

In [6]:
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT (m1.surname|| ', '|| m1.firstname)AS Member, 
            (m2.surname|| ', '|| m2.firstname) AS recommened_by
        FROM Members as m1
        LEFT JOIN Members as m2
        ON m1.recommendedby = m2.memid
        WHERE m2.memid != 0
        ORDER BY Member, recommened_by;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Bader, Florence', 'Stibbons, Ponder')
('Baker, Anne', 'Stibbons, Ponder')
('Baker, Timothy', 'Farrell, Jemima')
('Boothe, Tim', 'Rownam, Tim')
('Butters, Gerald', 'Smith, Darren')
('Coplin, Joan', 'Baker, Timothy')
('Crumpet, Erica', 'Smith, Tracy')
('Dare, Nancy', 'Joplette, Janice')
('Genting, Matthew', 'Butters, Gerald')
('Hunt, John', 'Purview, Millicent')
('Jones, David', 'Joplette, Janice')
('Jones, Douglas', 'Jones, David')
('Joplette, Janice', 'Smith, Darren')
('Mackenzie, Anna', 'Smith, Darren')
('Owen, Charles', 'Smith, Darren')
('Pinker, David', 'Farrell, Jemima')
('Purview, Millicent', 'Smith, Tracy')
('Rumney, Henrietta', 'Genting, Matthew')
('Sarwin, Ramnaresh', 'Bader, Florence')
('Smith, Jack', 'Smith, Darren')
('Stibbons, Ponder', 'Tracy, Burton')
('Worthington-Smyth, Henry', 'Smith, Tracy')

In [8]:
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
       SELECT f.name, COUNT(CASE WHEN memid > 0 THEN Bookid ELSE 'none' END)AS member_usage
    FROM Facilities as f
    LEFT JOIN Bookings as b
    USING (facid)
    WHERE memid > 0
    GROUP BY f.name
    ORDER BY f.name;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 344)
('Massage Room 1', 421)
('Massage Room 2', 27)
('Pool Table', 783)
('Snooker Table', 421)
('Squash Court', 195)
('Table Tennis', 385)
('Tennis Court 1', 308)
('Tennis Court 2', 276)

In [19]:
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
   SELECT f.name, COUNT(CASE WHEN memid > 0 THEN Bookid ELSE 'none' END)AS member_usage, 
   strftime('%m-%Y', starttime) AS 'MM/YYYY'
    FROM Facilities as f
    LEFT JOIN Bookings as b
    USING (facid)
    WHERE memid > 0
GROUP BY strftime('%m', starttime), f.name    
ORDER BY f.name, starttime;

        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 51, '07-2012')
('Badminton Court', 132, '08-2012')
('Badminton Court', 161, '09-2012')
('Massage Room 1', 77, '07-2012')
('Massage Room 1', 153, '08-2012')
('Massage Room 1', 191, '09-2012')
('Massage Room 2', 4, '07-2012')
('Massage Room 2', 9, '08-2012')
('Massage Room 2', 14, '09-2012')
('Pool Table', 103, '07-2012')
('Pool Table', 272, '08-2012')
('Pool Table', 408, '09-2012')
('Snooker Table', 68, '07-2012')
('Snooker Table', 154, '08-2012')
('Snooker Table', 199, '09-2012')
('Squash Court', 23, '07-2012')
('Squash Court', 85, '08-2012')
('Squash Court', 87, '09-2012')
('Table Tennis', 48, '07-2012')
('Table Tennis', 143, '08-2012')
('Table Tennis', 194, '09-2012')
('Tennis Court 1', 65, '07-2012')
('Tennis Court 1', 111, '08-2012')
('Tennis Court 1', 132, '09-2012')
('Tennis Court 2', 41, '07-2012')
('Tennis Court 2', 109, '08-2012')
('Tennis Court 2', 126, '09-2012')